version: '3'
services:
  jupyter:
    image: jupyter/datascience-notebook
    environment:
      JUPYTER_ENABLE_LAB: 1
    volumes:
      - ./workspace:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    tty: true
    stdin_open: true
